"""
Turn a completed run into the figures, tables, and macros the paper uses.

The important output is `results/paper_macros.tex`. Every quantity the
manuscript states is emitted there as a LaTeX macro, and the manuscript
cites the macro rather than a literal. A number can then only change by
re-running the experiment, which is what stopped the earlier drift where the
text quoted 30 on-chain records while the shipped log held 15.

`tools/check_paper_numbers.py` re-reads both files and fails if the .tex
contains a hard-coded figure that a macro should be carrying.
"""

from __future__ import annotations

import json
import statistics
from pathlib import Path
from typing import Any, Optional

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

plt.rcParams.update({
    "figure.dpi": 150,
    "savefig.dpi": 600,
    "font.size": 9,
    "axes.grid": True,
    "grid.alpha": 0.3,
    "axes.spines.top": False,
    "axes.spines.right": False,
})

PALETTE = ["#3f6fb5", "#c85a3f", "#4d8f6a", "#8a6fa8", "#b58a3f"]


# ======================================================================
# macros
# ======================================================================

def _fmt(x: Optional[float], places: int = 2, thousands: bool = False) -> str:
    if x is None:
        return "n/a"
    if thousands:
        return f"{x:,.0f}".replace(",", "{,}")
    return f"{x:.{places}f}"


# Macros the manuscript references. Any that a run did not produce are still
# emitted, as a loud placeholder, so the document always compiles and a
# missing measurement is visible on the page instead of failing the build
# with an undefined-control-sequence error three hours into a deadline.
REQUIRED_MACROS = [
    # environment
    "envDevice", "envTorch", "envGPU", "envCommit", "runProfile",
    # zkp
    "zkNumProofs", "zkGenMs", "zkGenStdMs", "zkVerifyMs", "zkVerifyStdMs",
    "zkProofBytes", "zkAcceptRate", "zkTamperRate", "zkModel", "zkDataset",
    "zkFingerprint", "zkNumAdversaries",
    # local EVM
    "evmVOneDeployGas", "evmVTwoDeployGas", "evmVOneLogGas", "evmVTwoLogGas",
    "evmVerifyOnlyGas", "evmRegisterGas", "evmTrustlessDeltaGas",
    "evmTrustlessDeltaPct",
    # mainnet projections
    "mainnetRecordUSDHigh", "mainnetRecordUSDMid", "mainnetRecordUSDLow",
]

PLACEHOLDER = r"\textbf{[PENDING]}"

# LaTeX control sequences are letters only -- \FB15k237Entities parses as \FB
# followed by stray body text, which fails in the preamble with a confusing
# "Missing \begin{document}". Datasets therefore get short alphabetic aliases
# rather than having their names mangled into macro keys.
DATASET_ALIAS = {
    "FB15k-237": "FB",
    "WN18RR": "WN",
}


def macro_key(name: str) -> str:
    """Alphabetic-only identifier safe to use in a control sequence."""
    if name in DATASET_ALIAS:
        return DATASET_ALIAS[name]
    digits = str.maketrans(
        {"0": "Zero", "1": "One", "2": "Two", "3": "Three", "4": "Four",
         "5": "Five", "6": "Six", "7": "Seven", "8": "Eight", "9": "Nine"}
    )
    return "".join(ch for ch in name.translate(digits) if ch.isalpha())


class MacroFile:
    """Accumulates \\newcommand definitions for the manuscript."""

    def __init__(self) -> None:
        self.lines: list[str] = []
        self.seen: set[str] = set()

    def add(self, name: str, value: str, comment: str = "") -> None:
        if not name.isalpha():
            raise ValueError(
                f"macro name {name!r} is not purely alphabetic; LaTeX would "
                "truncate it at the first non-letter. Use macro_key()."
            )
        if name in self.seen:
            raise ValueError(f"duplicate macro {name}")
        self.seen.add(name)
        suffix = f"  % {comment}" if comment else ""
        self.lines.append(f"\\newcommand{{\\{name}}}{{{value}}}{suffix}")

    def section(self, title: str) -> None:
        self.lines.append("")
        self.lines.append(f"% ---- {title} ----")

    def fill_missing(self) -> list[str]:
        """Emit placeholders for required macros this run did not measure."""
        missing = [m for m in REQUIRED_MACROS if m not in self.seen]
        if missing:
            self.section("NOT MEASURED IN THIS RUN -- rerun the relevant stage")
            for name in missing:
                self.add(name, PLACEHOLDER, "no measurement available")
        return missing

    def write(self, path: Path) -> None:
        missing = self.fill_missing()
        header = [
            "% ==================================================================",
            "% AUTO-GENERATED by src/reporting.py -- do not edit by hand.",
            "% Regenerate with: python run_all.py --stages report",
            "%",
            "% Every experimental number in the manuscript is defined here and",
            "% referenced by macro, so the text cannot drift from results/.",
            "% ==================================================================",
            "",
        ]
        path.write_text("\n".join(header + self.lines) + "\n", encoding="utf-8")
        print(f"  -> {path.name} ({len(self.seen)} macros)")
        if missing:
            print(f"     WARNING: {len(missing)} macro(s) unmeasured, "
                  f"emitted as {PLACEHOLDER}:")
            for name in missing:
                print(f"       - \\{name}")


# ======================================================================
# figures
# ======================================================================

def _save(fig, out: Path, stem: str) -> None:
    """Write every figure twice.

    Elsevier prefers vector artwork for line drawings, and a PDF scales to any
    column width without resampling. The PNG is kept for quick viewing and for
    anyone compiling with a toolchain that dislikes PDF includes.
    """
    fig.savefig(out / f"{stem}.pdf", bbox_inches="tight")
    fig.savefig(out / f"{stem}.png", bbox_inches="tight")
    plt.close(fig)
    print(f"  -> {stem}.pdf + {stem}.png")


def fig_training_curves(state: dict, out: Path) -> None:
    lp = state.get("link_prediction") or {}
    if not lp:
        return
    datasets = list(lp)
    fig, axes = plt.subplots(1, len(datasets), figsize=(5.5 * len(datasets), 3.4),
                             squeeze=False)
    for ax, ds in zip(axes[0], datasets):
        for i, (model, entry) in enumerate(lp[ds].items()):
            loss = (entry.get("history") or {}).get("loss") or []
            if loss:
                ax.plot(range(1, len(loss) + 1), loss,
                        label=model, color=PALETTE[i % len(PALETTE)], lw=1.5)
        ax.set_title(ds)
        ax.set_xlabel("Epoch")
        ax.set_ylabel("Training loss")
        ax.legend(frameon=False)
    fig.tight_layout()
    _save(fig, out, "training_curves")


def fig_metrics_comparison(state: dict, out: Path) -> None:
    lp = state.get("link_prediction") or {}
    if not lp:
        return
    metrics = ["MRR", "Hits@1", "Hits@3", "Hits@10"]
    datasets = list(lp)
    fig, axes = plt.subplots(1, len(datasets), figsize=(5.5 * len(datasets), 3.4),
                             squeeze=False)
    for ax, ds in zip(axes[0], datasets):
        models = list(lp[ds])
        width = 0.8 / max(len(models), 1)
        xs = range(len(metrics))
        for i, model in enumerate(models):
            vals = [lp[ds][model]["metrics"].get(m, 0.0) for m in metrics]
            ax.bar([x + i * width for x in xs], vals, width,
                   label=model, color=PALETTE[i % len(PALETTE)])
        ax.set_xticks([x + 0.4 - width / 2 for x in xs])
        ax.set_xticklabels(metrics)
        ax.set_ylabel("Score")
        ax.set_title(ds)
        ax.legend(frameon=False)
    fig.tight_layout()
    _save(fig, out, "metrics_comparison")


def fig_zkp_overhead(state: dict, out: Path) -> None:
    z = state.get("zkp")
    if not z:
        return
    gen = [t * 1000 for t in z.get("gen_times", [])]
    ver = [t * 1000 for t in z.get("verify_times", [])]
    if not gen or not ver:
        return

    fig, axes = plt.subplots(1, 3, figsize=(11, 3.2))
    axes[0].hist(gen, bins=40, color=PALETTE[0], edgecolor="white", lw=0.4)
    axes[0].axvline(statistics.fmean(gen), color=PALETTE[1], ls="--", lw=1.4,
                    label=f"mean {statistics.fmean(gen):.1f} ms")
    axes[0].set_xlabel("Proof generation (ms)")
    axes[0].set_ylabel("Count")
    axes[0].legend(frameon=False)

    axes[1].hist(ver, bins=40, color=PALETTE[2], edgecolor="white", lw=0.4)
    axes[1].axvline(statistics.fmean(ver), color=PALETTE[1], ls="--", lw=1.4,
                    label=f"mean {statistics.fmean(ver):.1f} ms")
    axes[1].set_xlabel("Proof verification (ms)")
    axes[1].legend(frameon=False)

    size = z.get("avg_proof_size_bytes", 0)
    axes[2].bar(["Proof"], [size], color=PALETTE[3], width=0.45)
    axes[2].set_ylabel("Bytes")
    axes[2].set_title(f"Wire size: {size:.0f} B")
    axes[2].grid(axis="x", visible=False)

    fig.tight_layout()
    _save(fig, out, "zkp_overhead")


def fig_gas_comparison(state: dict, out: Path) -> None:
    """V1 blind logging vs V2 chain-enforced verification."""
    t = state.get("onchain_verifier_test")
    if not t:
        return
    v1 = t["v1"]["log_gas_steady_mean"]
    v2 = t["v2"]["log_gas_steady_mean"]
    verify = t["v2"]["verify_gas_mean"]

    fig, axes = plt.subplots(1, 2, figsize=(9, 3.2))
    bars = axes[0].bar(
        ["V1\nlog only\n(trusts caller)", "V2\nverify + log\n(chain-enforced)"],
        [v1, v2], color=[PALETTE[4], PALETTE[0]], width=0.5,
    )
    for b, v in zip(bars, [v1, v2]):
        axes[0].text(b.get_x() + b.get_width() / 2, v * 1.01, f"{v:,.0f}",
                     ha="center", fontsize=8)
    axes[0].set_ylabel("Gas per record")
    axes[0].set_title(f"Cost of trustlessness: +{v2 - v1:,.0f} gas "
                      f"({(v2 - v1) / v1 * 100:+.1f}%)")

    sep = state.get("sepolia") or {}
    if sep.get("num_tx"):
        gas = [x for x in [sep.get("first_tx_gas"), sep.get("steady_state_avg_gas")]]
        axes[1].bar(["First record\n(cold slots)", "Steady state"], gas,
                    color=[PALETTE[1], PALETTE[2]], width=0.5)
        for i, v in enumerate(gas):
            axes[1].text(i, v * 1.01, f"{v:,.0f}", ha="center", fontsize=8)
        axes[1].set_title(f"Measured on Sepolia ({sep['num_tx']} records)")
    else:
        axes[1].bar(["verifyProof\n(crypto only)", "verifyAndLog\n(with storage)"],
                    [verify, v2], color=[PALETTE[3], PALETTE[0]], width=0.5)
        axes[1].set_title("In-memory EVM breakdown")
    axes[1].set_ylabel("Gas")

    fig.tight_layout()
    _save(fig, out, "gas_comparison")


def fig_pipeline_timing(state: dict, out: Path) -> None:
    timings = {k: v for k, v in (state.get("timings") or {}).items() if k != "total"}
    if not timings:
        return
    labels = list(timings)
    vals = [timings[k] for k in labels]
    fig, ax = plt.subplots(figsize=(6.5, 3.0))
    ax.barh(labels, vals, color=PALETTE[0], height=0.55)
    total = sum(vals)
    for i, v in enumerate(vals):
        ax.text(v, i, f"  {v:,.0f}s ({v / total * 100:.1f}%)", va="center", fontsize=8)
    ax.set_xlabel("Wall-clock seconds")
    ax.set_xlim(0, max(vals) * 1.35)
    ax.grid(axis="y", visible=False)
    fig.tight_layout()
    _save(fig, out, "pipeline_timing")


# ======================================================================
# tables
# ======================================================================

def table_link_prediction(state: dict) -> str:
    lp = state.get("link_prediction") or {}
    rows = []
    for ds, models in lp.items():
        rows.append(r"\midrule")
        rows.append(rf"\multicolumn{{5}}{{l}}{{\emph{{{ds}}}}} \\")
        best = max(models, key=lambda m: models[m]["metrics"]["MRR"]) if models else None
        for model, entry in models.items():
            m = entry["metrics"]
            cells = [f"{m[k]:.4f}" for k in ("MRR", "Hits@1", "Hits@3", "Hits@10")]
            if model == best:
                cells = [rf"\textbf{{{c}}}" for c in cells]
                name = rf"\textbf{{{model}}}"
            else:
                name = model
            rows.append(f"{name} & " + " & ".join(cells) + r" \\")
    body = "\n".join(rows)
    return (
        "\\begin{tabular}{lcccc}\n\\toprule\n"
        "\\textbf{Model} & \\textbf{MRR} & \\textbf{Hits@1} & "
        "\\textbf{Hits@3} & \\textbf{Hits@10} \\\\\n"
        f"{body}\n\\bottomrule\n\\end{{tabular}}\n"
    )


def table_datasets(state: dict) -> str:
    ds = state.get("datasets") or {}
    rows = [
        f"{d['name']} & {d['entities']:,} & {d['relations']:,} & "
        f"{d['train']:,} & {d['valid']:,} & {d['test']:,} \\\\".replace(",", "{,}")
        for d in ds.values()
    ]
    return (
        "\\begin{tabular}{lccccc}\n\\toprule\n"
        "\\textbf{Dataset} & \\textbf{Entities} & \\textbf{Relations} & "
        "\\textbf{Train} & \\textbf{Valid} & \\textbf{Test} \\\\\n\\midrule\n"
        + "\n".join(rows)
        + "\n\\bottomrule\n\\end{tabular}\n"
    )


def table_soundness(state: dict) -> str:
    z = state.get("zkp") or {}
    s = z.get("soundness") or {}
    labels = {
        "A1_response_tamper": "A1: response scalar $s_v$ perturbed",
        "A2_prediction_swap": "A2: answered entity swapped after proving",
        "A3_score_inflation": "A3: reported confidence inflated",
        "A4_commitment_swap": "A4: commitment replaced with an unopenable one",
        "A5_offcurve_point": "A5: announcement forced off the curve",
        "A6_unregistered_model": "A6: honest proof for an unregistered model",
    }

    def label_for(key: str) -> str:
        """Never emit a raw key: underscores would break out of text mode."""
        return labels.get(key, key.replace("_", " "))

    rows = [
        f"{label_for(k)} & {v['trials']:,} & {v['rejected']:,} & "
        f"{v['rate']*100:.1f}\\% \\\\".replace(",", "{,}")
        for k, v in s.items()
    ]
    return (
        "\\begin{tabular}{lccc}\n\\toprule\n"
        "\\textbf{Adversary} & \\textbf{Trials} & \\textbf{Rejected} & "
        "\\textbf{Detection} \\\\\n\\midrule\n"
        + "\n".join(rows)
        + "\n\\bottomrule\n\\end{tabular}\n"
    )


def table_onchain(state: dict) -> str:
    """The paper's headline table: what chain-enforced verification costs.

    V1 stores whatever boolean the caller asserts; V2 re-derives the
    Fiat-Shamir challenge and checks the group equation inside the EVM,
    reverting if it fails. The interesting quantity is the difference.
    """
    t = state.get("onchain_verifier_test")
    if not t:
        return "% no on-chain verifier results in state\n"

    v1, v2 = t["v1"], t["v2"]

    def g(x) -> str:
        return f"{x:,.0f}".replace(",", "{,}") if x is not None else "--"

    delta = t.get("cost_of_trustlessness_gas")
    pct = t.get("cost_of_trustlessness_pct")

    rows = [
        f"Contract deployment & {g(v1['deploy_gas'])} & {g(v2['deploy_gas'])} \\\\",
        f"Model registration & -- & {g(v2.get('register_gas'))} \\\\",
        f"Proof verification (call only) & -- & {g(v2.get('verify_gas_mean'))} \\\\",
        "\\midrule",
        f"Record, first call & {g(v1['log_gas_first'])} & {g(v2['log_gas_first'])} \\\\",
        f"Record, steady state & {g(v1['log_gas_steady_mean'])} & "
        f"{g(v2['log_gas_steady_mean'])} \\\\",
    ]
    caption_row = (
        f"\\multicolumn{{3}}{{l}}{{\\footnotesize Cost of trustlessness: "
        f"$+{g(delta)}$ gas ({pct:+.2f}\\%) per record.}} \\\\"
        if delta is not None and pct is not None else ""
    )

    return (
        "\\begin{tabular}{lrr}\n\\toprule\n"
        "\\textbf{Operation} & \\textbf{V1 (unverified)} & "
        "\\textbf{V2 (chain-verified)} \\\\\n\\midrule\n"
        + "\n".join(rows)
        + "\n\\bottomrule\n"
        + (caption_row + "\n" if caption_row else "")
        + "\\end{tabular}\n"
    )


# ======================================================================
# driver
# ======================================================================

def build_all(state: dict, results_dir: Path) -> None:
    results_dir.mkdir(parents=True, exist_ok=True)

    fig_training_curves(state, results_dir)
    fig_metrics_comparison(state, results_dir)
    fig_zkp_overhead(state, results_dir)
    fig_gas_comparison(state, results_dir)
    fig_pipeline_timing(state, results_dir)

    tables = {
        "table_datasets.tex": table_datasets(state),
        "table_link_prediction.tex": table_link_prediction(state),
        "table_soundness.tex": table_soundness(state),
        "table_onchain.tex": table_onchain(state),
    }
    for name, body in tables.items():
        (results_dir / name).write_text(body, encoding="utf-8")
        print(f"  -> {name}")

    m = MacroFile()

    # ---- environment ----
    env = state.get("environment", {})
    m.section("environment")
    m.add("envDevice", str(env.get("device", "cpu")).upper())
    m.add("envTorch", str(env.get("torch", "n/a")))
    m.add("envGPU", str(env.get("gpu", "CPU only")))
    m.add("envCommit", str(env.get("git_commit") or "n/a"))
    m.add("runProfile", str(state.get("profile", "n/a")))

    # ---- datasets ----
    ds = state.get("datasets") or {}
    m.section("datasets")
    m.add("numDatasets", str(len(ds)))
    for d in ds.values():
        key = macro_key(d["name"])
        m.add(f"{key}Entities", _fmt(d["entities"], thousands=True))
        m.add(f"{key}Relations", _fmt(d["relations"], thousands=True))
        m.add(f"{key}Train", _fmt(d["train"], thousands=True))
        m.add(f"{key}Valid", _fmt(d["valid"], thousands=True))
        m.add(f"{key}Test", _fmt(d["test"], thousands=True))

    # ---- link prediction ----
    lp = state.get("link_prediction") or {}
    m.section("link prediction")
    for ds_name, models in lp.items():
        key = macro_key(ds_name)
        for model, entry in models.items():
            mm = entry["metrics"]
            for metric, mac in [("MRR", "MRR"), ("Hits@1", "HitsOne"),
                                ("Hits@3", "HitsThree"), ("Hits@10", "HitsTen")]:
                m.add(f"{key}{model}{mac}", _fmt(mm[metric], 4))
        if models:
            best = max(models, key=lambda k: models[k]["metrics"]["MRR"])
            m.add(f"{key}BestModel", best)
            m.add(f"{key}BestMRR", _fmt(models[best]["metrics"]["MRR"], 4))

    # ---- ZKP ----
    z = state.get("zkp") or {}
    if z:
        m.section("zero-knowledge proofs")
        m.add("zkNumProofs", _fmt(z.get("num_proofs"), thousands=True))
        m.add("zkGenMs", _fmt(z.get("avg_gen_time", 0) * 1000))
        m.add("zkGenStdMs", _fmt(z.get("std_gen_time", 0) * 1000))
        m.add("zkVerifyMs", _fmt(z.get("avg_verify_time", 0) * 1000))
        m.add("zkVerifyStdMs", _fmt(z.get("std_verify_time", 0) * 1000))
        m.add("zkProofBytes", _fmt(z.get("avg_proof_size_bytes"), 0))
        m.add("zkAcceptRate", _fmt(z.get("verification_rate", 0) * 100, 1))
        m.add("zkTamperRate", _fmt(z.get("tamper_detection_rate", 0) * 100, 1))
        m.add("zkModel", str(z.get("model", "n/a")))
        m.add("zkDataset", str(z.get("dataset", "n/a")))
        m.add("zkFingerprint", str(z.get("model_fingerprint", ""))[:16])
        m.add("zkNumAdversaries", str(len(z.get("soundness") or {})))

    # ---- local EVM ----
    t = state.get("onchain_verifier_test")
    if t:
        m.section("in-memory EVM verification")
        m.add("evmVOneDeployGas", _fmt(t["v1"]["deploy_gas"], thousands=True))
        m.add("evmVTwoDeployGas", _fmt(t["v2"]["deploy_gas"], thousands=True))
        m.add("evmVOneLogGas", _fmt(t["v1"]["log_gas_steady_mean"], thousands=True))
        m.add("evmVTwoLogGas", _fmt(t["v2"]["log_gas_steady_mean"], thousands=True))
        m.add("evmVerifyOnlyGas", _fmt(t["v2"]["verify_gas_mean"], thousands=True))
        m.add("evmRegisterGas", _fmt(t["v2"].get("register_gas"), thousands=True))
        m.add("evmTrustlessDeltaGas", _fmt(t["cost_of_trustlessness_gas"], thousands=True))
        m.add("evmTrustlessDeltaPct", _fmt(t["cost_of_trustlessness_pct"], 1))
        m.add("evmNumAdversariesOnchain",
              str(len([k for k, v in (t.get("soundness") or {}).items()
                       if "inert" not in str(v)])))

    # ---- Sepolia ----
    s = state.get("sepolia") or {}
    if s.get("num_tx"):
        m.section("sepolia")
        m.add("sepoliaContract", str(s.get("contract_address", "")))
        m.add("sepoliaContractShort",
              f"{str(s.get('contract_address',''))[:6]}...{str(s.get('contract_address',''))[-4:]}")
        m.add("sepoliaVersion", str(s.get("contract_version", "v2")))
        m.add("sepoliaNumTx", _fmt(s["num_tx"], thousands=True))
        m.add("sepoliaFirstGas", _fmt(s.get("first_tx_gas"), thousands=True))
        m.add("sepoliaSteadyGas", _fmt(s.get("steady_state_avg_gas"), thousands=True))
        m.add("sepoliaSteadyStdGas", _fmt(s.get("steady_state_std_gas"), 0))
        m.add("sepoliaTotalGas", _fmt(s.get("total_gas_used"), thousands=True))
        m.add("sepoliaTotalCostETH", _fmt(s.get("total_cost_eth"), 5))
        m.add("sepoliaLatency", _fmt(s.get("median_latency_s"), 1))
        dep = s.get("deployment") or {}
        if dep:
            m.add("sepoliaDeployGas", _fmt(dep.get("deploy_gas_used"), thousands=True))
            m.add("sepoliaDeployCostETH", _fmt(dep.get("deploy_cost_eth"), 5))
            m.add("sepoliaDeployTx", str(dep.get("deploy_tx", "")))
        ctx = s.get("context") or {}
        vg = ctx.get("verify_only_gas_mean")
        if vg:
            m.add("sepoliaVerifyOnlyGas", _fmt(vg, thousands=True))
        reg = ctx.get("registration") or {}
        if reg.get("gas_used"):
            m.add("sepoliaRegisterGas", _fmt(reg["gas_used"], thousands=True))
        if reg.get("block_number"):
            m.add("sepoliaRegisterBlock", _fmt(reg["block_number"], thousands=True))
        if ctx.get("model_fingerprint"):
            m.add("sepoliaWeightDigest", str(ctx["model_fingerprint"])[:16])


    # ---- mainnet projections ----
    #
    # Derived from measured gas at stated prices; these are projections, not
    # measurements, and the paper labels them as such. Sepolia gas is
    # preferred when available because it reflects real consensus execution;
    # otherwise the in-memory EVM figure is used, which matches Sepolia
    # closely (both reproduce the same deployment gas exactly).
    steady_gas = None
    basis = None
    if s.get("steady_state_avg_gas"):
        steady_gas, basis = s["steady_state_avg_gas"], "sepolia"
    elif t:
        steady_gas, basis = t["v2"]["log_gas_steady_mean"], "in-memory EVM"
    if steady_gas:
        m.section(f"mainnet projections (basis: {basis}, $3000/ETH)")
        for gwei, label in [(30, "High"), (10, "Mid"), (5, "Low")]:
            m.add(f"mainnetRecordUSD{label}",
                  _fmt(steady_gas * gwei * 1e-9 * 3000, 2),
                  f"{gwei} gwei, projection from {basis}")

    # ---- timings ----
    timings = state.get("timings") or {}
    if timings:
        m.section("wall-clock timings")
        for k, v in timings.items():
            key = "".join(p.capitalize() for p in k.replace("-", "_").split("_"))
            m.add(f"time{key}", _fmt(v, 1))

        # The stage timers measure one invocation, so a model restored from a
        # checkpoint contributes nothing to timeTrain even though it was
        # trained. Quoting that in the paper would understate the cost of
        # reproducing this work. These macros sum the per-model times recorded
        # with the models themselves, so they describe the whole experiment
        # however many sittings it took.
        lp = state.get("link_prediction") or {}
        train_s = sum(e["history"]["total_time"]
                      for models in lp.values() for e in models.values())
        eval_s = sum(e["metrics"]["eval_time"]
                     for models in lp.values() for e in models.values())
        if train_s:
            other_s = sum(v for k, v in timings.items() if k != "train")
            m.add("timeTrainWork", _fmt(train_s, 1),
                  "summed over every model, checkpoint reuse excluded")
            m.add("timeEvalWork", _fmt(eval_s, 1))
            m.add("timeEndToEnd", _fmt(train_s + eval_s + other_s, 1))
            m.add("timeEndToEndMin", _fmt((train_s + eval_s + other_s) / 60, 1))
            m.add("pctCryptoOverhead",
                  _fmt(100.0 * other_s / (train_s + eval_s + other_s), 1))

    m.write(results_dir / "paper_macros.tex")
